### ISSUE TITLE
Usage of non default colors breaks styling

### ISSUE THREAD

**Issue by 188599** [heliomarpm/ion-calendar#7]
### Describe the bug

Passing a non default color to the component breaks the styling for selection in the calendar, and marker for the current date.

### Expected behavior

The pre-forked version of the library supported the usage of non-default colors, so I assumed this would too.

### Additional context/Screenshots
Without selecting any color:

<img src="https://github.com/user-attachments/assets/3482d98f-90e2-4d53-a1a5-2e67f5c13f2f" width="400">

With non default color:

<img src="https://github.com/user-attachments/assets/ea79c348-1fbd-4c6a-9acc-c89fd8875c7a" width="400">

**Comment by heliomarpm** [comment]
Can you send a code example please?

**Comment by 188599** [comment]
Well, I ended up doing this to make it work, which I'm not sure if its the intended way, but it works.

```ts
    const options: ICalendarModalOptions = {
      //...
      cssClass: 'ion-my-non-default-color',
      color: 'custom',
    };
```

```scss
  ion-calendar-modal {
    --ion-color-custom: var(--ion-color-base);
    --ion-color-custom-rgb: var(--ion-color-base-rgb);
    --ion-color-custom-contrast: var(--ion-color-contrast);
    --ion-color-custom-contrast-rgb: var(--ion-color-contrast-rgb);
    --ion-color-custom-shade: var(--ion-color-shade);
    --ion-color-custom-tint: var(--ion-color-tint);
  }
```

If this is intended, I think it would be good to add this as an example to the readme section.
